# Generated by Django 3.0.6 on 2020-05-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('PictureId', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Id')),
                ('PictureName', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
    ]
